FROM ghcr.io/mchristopher/canvas-lms-docker:sha-e1b9aa8

# RUN set -eux; \
#   yarn gulp rev

# RUN touch app/stylesheets/_brandable_variables_defaults_autogenerated.scss \
#     && touch log/production.log \
#     && COMPILE_ASSETS_API_DOCS=0 \
#        COMPILE_ASSETS_BRAND_CONFIGS=0 \
#        bundle exec rails canvas:compile_assets

#RUN bin/rails canvas:compile_assets --trace

RUN touch log/production.log
