development:
  bucket_name: development-bucket
  access_key_id: access_key
  secret_access_key: secret_key

test:
  bucket_name: test-bucket
  access_key_id: access_key
  secret_access_key: secret_key

production:
  bucket_name: <%= ENV['AWS_BUCKET_NAME'] %>
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  # The default endpoint is s3.amazonaws.com, which will technically work
  # for any region, but will require a bounce through a US region, so will
  # be slower. It's recommended that you set this for whichever region
  # your bucket is in.
  # s3_endpoint: s3-eu-west-1.amazonaws.com
