production:
  enable_starttls_auto: true
  address: "<%= ENV['SMTP_SERVER'] %>"
  port: "<%= ENV['SMTP_PORT'] %>"
  user_name: "<%= ENV['SMTP_USER_NAME'] %>"
  password: "<%= ENV['SMTP_PASSWORD'] %>"
  authentication: "plain"
  domain: "<%= ENV['SMTP_DOMAIN'] %>"
  outgoing_address: "<%= ENV['SMTP_SENDER'] %>"
  default_name: "Canvas"
